### ISSUE TITLE
Update for Finagle 6.42.0

### ISSUE THREAD

**Issue by od0** [finagle/finagle-oauth2#19]
Updating to Finagle 6.42.0 leads to errors such as this:
`java.lang.NoSuchMethodError: com.twitter.finagle.http.HeaderMap.getAll`

Would it be possible to get a new compatible release?

**Comment by vkostyukov** [comment]
Sure! Do you mind opening a PR with Finagle dependency bumped up?

**Comment by vkostyukov** [comment]
I decided to go ahead and bump Finagle myself - I still need it for Finch. Thanks for the report @od0! See #20.

**Comment by od0** [comment]
@vkostyukov thanks! Just saw the notification but will open a PR next time 👍
