### ISSUE TITLE
OAuth2 Implicit grant type

### ISSUE THREAD

**Issue by mauropalsgraaf** [finagle/finagle-oauth2#25]
Not sure where to ask this question, I'm about to implement OAuth2 for my application and the suitable grant type for my application is implicit. I've noticed that this library is not supporting it (or am I missing it), but the scala-oauth library does have it. 

Is there a particular reason why it's not present and can I give it a shot to add it to this project?

**Comment by vkostyukov** [comment]
Thanks @mauropalsgraaf!

Yeah, finagle-oauth2 was inspired (forked) from scala-oauth2 several years ago. At that time, scala-oauth2 was purely synchronous, which was a deal-breaker for adoption within a Finagle services (that are async by nature). As far as I know, scala-oauth2 now works with Scala futures, which makes it quite usable within Finagle. That said, I suggest you try using it directly (given the conversions between futures).

In the meantime, I should find some time to restructure finagle-oauth2 just to be a simple wrapper around scala-oauth2 instead.

**Comment by mauropalsgraaf** [comment]
Hey Vladimir,

Thanks for your response, I'll try to use scala-oauth2 directly. If there is anything I can help with, feel free to ask. I'm not an expert in Scala, but would love to help.

I'm closing this issue since my questions are answered
