### ISSUE TITLE
Releasing with Bintray

### ISSUE THREAD

**Issue by vkostyukov** [finagle/finagle-oauth2#9]
Instead of using custom server.

**Comment by trnl** [comment]
@vkostyukov, any news on this? May be any help required?

**Comment by vkostyukov** [comment]
I tried to do it some time ago but failed. Bintray is confusing as hell. Should probably try again. @trnl do you use it?

**Comment by vkostyukov** [comment]
Okay. I just published the version 0.1.4 to MC. Should be synced in a couple of hours.
